apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: guestbook
  newName: ghcr.io/isacssouza/guestbook
  newTag: 4f2d81212f3446db257e8dea6cea45105c1592ed
