apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: guestbook
  newName: ghcr.io/isouza-daitan/guestbook
  newTag: 5498c19fbb924d452006a844361cafa4fa067390
