apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
spec:
  destination:
    namespace: guestbook-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/isacssouza/guestbook-go-config
    path: overlays/staging
    targetRevision: HEAD
    kustomize:
      images:
        - guestbook-image=ghcr.io/isacssouza/guestbook:v1.7
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
