apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-pr
spec:
  destination:
    namespace: guestbook-pr
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/isacssouza/guestbook-go-config
    path: overlays/pr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
