apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guestbook-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/isacssouza/guestbook-go-config
    path: overlays/prod
    targetRevision: HEAD
    kustomize:
      images:
        - guestbook-image=ghcr.io/isacssouza/guestbook:v1.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true